Description: Configuration for Adapter participant for SIL Kit Adapter veIPC demo
ParticipantName: SilKitAdapterVeIpc
Middleware:
  RegistryUri: silkit://localhost:8501
Logging:
  Sinks:
  - Type: Stdout
    Level: Debug
